//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentSupervisor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgentSupervisor.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string AboutButtonOK {
            get {
                return ResourceManager.GetString("AboutButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Supervisor Contributors.
        /// </summary>
        public static string AboutCopyright {
            get {
                return ResourceManager.GetString("AboutCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Windows system tray application that monitors
        ///GitHub pull request reviews and sends desktop notifications..
        /// </summary>
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutFormTitle {
            get {
                return ResourceManager.GetString("AboutFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Supervisor.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by {0} • {1}.
        /// </summary>
        public static string DetailAuthorDateFormat {
            get {
                return ResourceManager.GetString("DetailAuthorDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中文 (Chinese).
        /// </summary>
        public static string LanguageChinese {
            get {
                return ResourceManager.GetString("LanguageChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW.
        /// </summary>
        public static string MainWindowBadgeNew {
            get {
                return ResourceManager.GetString("MainWindowBadgeNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark All as Read.
        /// </summary>
        public static string MainWindowButtonMarkAllRead {
            get {
                return ResourceManager.GetString("MainWindowButtonMarkAllRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as read.
        /// </summary>
        public static string MainWindowContextMenuMarkAsRead {
            get {
                return ResourceManager.GetString("MainWindowContextMenuMarkAsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string MainWindowContextMenuOpen {
            get {
                return ResourceManager.GetString("MainWindowContextMenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: {0} review request(s) | New: {1}.
        /// </summary>
        public static string MainWindowStatusFormat {
            get {
                return ResourceManager.GetString("MainWindowStatusFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No review requests.
        /// </summary>
        public static string MainWindowStatusNoRequests {
            get {
                return ResourceManager.GetString("MainWindowStatusNoRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Requests by Copilots.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuItemAbout {
            get {
                return ResourceManager.GetString("MenuItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string MenuItemCheckForUpdates {
            get {
                return ResourceManager.GetString("MenuItemCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuItemExit {
            get {
                return ResourceManager.GetString("MenuItemExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Polling.
        /// </summary>
        public static string MenuItemPausePolling {
            get {
                return ResourceManager.GetString("MenuItemPausePolling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll at Once.
        /// </summary>
        public static string MenuItemPollAtOnce {
            get {
                return ResourceManager.GetString("MenuItemPollAtOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume Polling.
        /// </summary>
        public static string MenuItemResumePolling {
            get {
                return ResourceManager.GetString("MenuItemResumePolling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Requests by Copilots.
        /// </summary>
        public static string MenuItemReviewRequests {
            get {
                return ResourceManager.GetString("MenuItemReviewRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MenuItemSettings {
            get {
                return ResourceManager.GetString("MenuItemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Supervisor is already running.
        ///
        ///Please check the system tray for the application icon..
        /// </summary>
        public static string MessageAlreadyRunning {
            get {
                return ResourceManager.GetString("MessageAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Supervisor Already Running.
        /// </summary>
        public static string MessageBoxTitleAlreadyRunning {
            get {
                return ResourceManager.GetString("MessageBoxTitleAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Error.
        /// </summary>
        public static string MessageBoxTitleConfigurationError {
            get {
                return ResourceManager.GetString("MessageBoxTitleConfigurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Error.
        /// </summary>
        public static string MessageBoxTitleConnectionError {
            get {
                return ResourceManager.GetString("MessageBoxTitleConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxTitleError {
            get {
                return ResourceManager.GetString("MessageBoxTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Updates Available.
        /// </summary>
        public static string MessageBoxTitleNoUpdatesAvailable {
            get {
                return ResourceManager.GetString("MessageBoxTitleNoUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polling Error.
        /// </summary>
        public static string MessageBoxTitlePollingError {
            get {
                return ResourceManager.GetString("MessageBoxTitlePollingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polling Status.
        /// </summary>
        public static string MessageBoxTitlePollingStatus {
            get {
                return ResourceManager.GetString("MessageBoxTitlePollingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Release Update Available.
        /// </summary>
        public static string MessageBoxTitlePreReleaseUpdateAvailable {
            get {
                return ResourceManager.GetString("MessageBoxTitlePreReleaseUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string MessageBoxTitleSuccess {
            get {
                return ResourceManager.GetString("MessageBoxTitleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        public static string MessageBoxTitleUpdateAvailable {
            get {
                return ResourceManager.GetString("MessageBoxTitleUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Check Failed.
        /// </summary>
        public static string MessageBoxTitleUpdateCheckFailed {
            get {
                return ResourceManager.GetString("MessageBoxTitleUpdateCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error.
        /// </summary>
        public static string MessageBoxTitleValidationError {
            get {
                return ResourceManager.GetString("MessageBoxTitleValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Required.
        /// </summary>
        public static string MessageBoxTitleWarning {
            get {
                return ResourceManager.GetString("MessageBoxTitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to GitHub. Please check your Personal Access Token..
        /// </summary>
        public static string MessageConnectionFailed {
            get {
                return ResourceManager.GetString("MessageConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the application for the language change to take full effect..
        /// </summary>
        public static string MessageLanguageChangeRequiresRestart {
            get {
                return ResourceManager.GetString("MessageLanguageChangeRequiresRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are running the latest version..
        /// </summary>
        public static string MessageNoUpdatesAvailable {
            get {
                return ResourceManager.GetString("MessageNoUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data polling callback is not configured..
        /// </summary>
        public static string MessagePollingNotConfigured {
            get {
                return ResourceManager.GetString("MessagePollingNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data polling paused.
        /// </summary>
        public static string MessagePollingPaused {
            get {
                return ResourceManager.GetString("MessagePollingPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data polling resumed.
        /// </summary>
        public static string MessagePollingResumed {
            get {
                return ResourceManager.GetString("MessagePollingResumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy URL is required when proxy is enabled..
        /// </summary>
        public static string MessageProxyValidationFailed {
            get {
                return ResourceManager.GetString("MessageProxyValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved successfully..
        /// </summary>
        public static string MessageSettingsSaved {
            get {
                return ResourceManager.GetString("MessageSettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Access Token is required to run the application..
        /// </summary>
        public static string MessageTokenRequired {
            get {
                return ResourceManager.GetString("MessageTokenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Access Token is required..
        /// </summary>
        public static string MessageTokenValidationFailed {
            get {
                return ResourceManager.GetString("MessageTokenValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New PR Review - {0}.
        /// </summary>
        public static string NotificationNewPRReview {
            get {
                return ResourceManager.GetString("NotificationNewPRReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR #{0} - {1}
        ///Reviewer: {2}.
        /// </summary>
        public static string NotificationPRFormat {
            get {
                return ResourceManager.GetString("NotificationPRFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} is now available!
        ///Published: {1}.
        /// </summary>
        public static string NotificationUpdateFormat {
            get {
                return ResourceManager.GetString("NotificationUpdateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SettingsButtonCancel {
            get {
                return ResourceManager.GetString("SettingsButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SettingsButtonSave {
            get {
                return ResourceManager.GetString("SettingsButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsFormTitle {
            get {
                return ResourceManager.GetString("SettingsFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Desktop Notifications.
        /// </summary>
        public static string SettingsLabelEnableNotifications {
            get {
                return ResourceManager.GetString("SettingsLabelEnableNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string SettingsLabelLanguage {
            get {
                return ResourceManager.GetString("SettingsLabelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max History Entries:.
        /// </summary>
        public static string SettingsLabelMaxHistory {
            get {
                return ResourceManager.GetString("SettingsLabelMaxHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polling Interval (seconds):.
        /// </summary>
        public static string SettingsLabelPollingInterval {
            get {
                return ResourceManager.GetString("SettingsLabelPollingInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Settings.
        /// </summary>
        public static string SettingsLabelProxyGroup {
            get {
                return ResourceManager.GetString("SettingsLabelProxyGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy URL (e.g., http://proxy:8080):.
        /// </summary>
        public static string SettingsLabelProxyUrl {
            get {
                return ResourceManager.GetString("SettingsLabelProxyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show token.
        /// </summary>
        public static string SettingsLabelShowToken {
            get {
                return ResourceManager.GetString("SettingsLabelShowToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub Personal Access Token:.
        /// </summary>
        public static string SettingsLabelToken {
            get {
                return ResourceManager.GetString("SettingsLabelToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Proxy.
        /// </summary>
        public static string SettingsLabelUseProxy {
            get {
                return ResourceManager.GetString("SettingsLabelUseProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        public static string StatusCheckingForUpdates {
            get {
                return ResourceManager.GetString("StatusCheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected as {0}.
        /// </summary>
        public static string StatusConnectedAs {
            get {
                return ResourceManager.GetString("StatusConnectedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to GitHub....
        /// </summary>
        public static string StatusConnecting {
            get {
                return ResourceManager.GetString("StatusConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string StatusError {
            get {
                return ResourceManager.GetString("StatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring restarted.
        /// </summary>
        public static string StatusMonitoringRestarted {
            get {
                return ResourceManager.GetString("StatusMonitoringRestarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused - {0} pending review(s) - {1} unread.
        /// </summary>
        public static string StatusPausedFormat {
            get {
                return ResourceManager.GetString("StatusPausedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} pending review(s) - {1} unread.
        /// </summary>
        public static string StatusPendingReviews {
            get {
                return ResourceManager.GetString("StatusPendingReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polling data....
        /// </summary>
        public static string StatusPollingData {
            get {
                return ResourceManager.GetString("StatusPollingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to open the download page in your browser?.
        /// </summary>
        public static string UpdateMessageDownloadPrompt {
            get {
                return ResourceManager.GetString("UpdateMessageDownloadPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version ({0}) is available!.
        /// </summary>
        public static string UpdateMessageNewVersionAvailable {
            get {
                return ResourceManager.GetString("UpdateMessageNewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It may contain bugs or incomplete features..
        /// </summary>
        public static string UpdateMessagePreReleaseDetails {
            get {
                return ResourceManager.GetString("UpdateMessagePreReleaseDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ WARNING: This is a pre-release version (alpha/beta)..
        /// </summary>
        public static string UpdateMessagePreReleaseWarning {
            get {
                return ResourceManager.GetString("UpdateMessagePreReleaseWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published: {0}.
        /// </summary>
        public static string UpdateMessagePublishedDate {
            get {
                return ResourceManager.GetString("UpdateMessagePublishedDate", resourceCulture);
            }
        }
    }
}
